#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
upstream="$root/upstream/solar"
runtime="${1:-$root/build/solar-runtime}"

bash "$root/scripts/build_solar.sh"

rm -rf "$runtime"
mkdir -p "$runtime/bin" "$runtime/src" "$runtime/metadata"

cp "$upstream/bin/solar" "$runtime/bin/solar"
cp "$upstream/LICENSE" "$runtime/LICENSE"
cp "$upstream/README.md" "$runtime/README.upstream.md"
cp "$root/upstream/manifest.json" "$runtime/manifest.json"
cp "$upstream/src/"*.cpp "$runtime/src/"
cp "$upstream/src/"*.hpp "$runtime/src/"
cp "$upstream/src/makefile" "$runtime/src/"

python3 "$root/scripts/write_runtime_metadata.py" "$runtime/metadata"

cat > "$runtime/README.md" <<'EOF'
# SOLAR Slim Runtime

This directory is generated by `scripts/export_runtime.sh`.

It intentionally excludes upstream SOLAR's large `tests/` directory and Git
history. It keeps only the executable, source needed to rebuild the executable,
license/readme files, OptiProfiler metadata, and the upstream manifest.

Language-specific wrapper repositories may copy this runtime source without
committing `bin/solar` or `src/*.o`; those generated files should be rebuilt by
CI, the server, or the user's local machine.
EOF

du -sh "$runtime"
echo "Exported slim SOLAR runtime: $runtime"
